[package]
name = "accesskit_winit"
version = "0.14.4"
authors = ["Matt Campbell <mattcampbell@pobox.com>"]
license = "Apache-2.0"
description = "AccessKit UI accessibility infrastructure: winit adapter"
categories = ["gui"]
keywords = ["gui", "ui", "accessibility", "winit"]
repository = "https://github.com/AccessKit/accesskit"
readme = "README.md"
edition = "2021"

[package.metadata.docs.rs]
features = ["winit/x11", "winit/wayland"]

[features]
default = ["accesskit_unix", "async-io"]
async-io = ["accesskit_unix/async-io"]
tokio = ["accesskit_unix/tokio"]

[dependencies]
accesskit = { version = "0.11.2", path = "../../common" }
#winit = { version = "0.28", default-features = false }
winit = { git = "https://github.com/Riateche/winit.git", branch = "fix-wait-until", default-features = false }
raw-window-handle = "0.5"

[target.'cfg(target_os = "windows")'.dependencies]
accesskit_windows = { version = "0.14.3", path = "../windows" }

[target.'cfg(target_os = "macos")'.dependencies]
accesskit_macos = { version = "0.9.0", path = "../macos" }

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
accesskit_unix = { version = "0.5.2", path = "../unix", optional = true, default-features = false }

[dev-dependencies]
#winit = "0.28"
winit = { git = "https://github.com/Riateche/winit.git", branch = "fix-wait-until" }
